import type {
  GeneratorConfig,
  NormalizedSchema,
  OpenApiModel,
} from './types.js';
import { renderArrayConstraints } from './validations/render-arrays.js';
import { renderNumberConstraints } from './validations/render-numbers.js';
import { renderObjectConstraints } from './validations/render-objects.js';
import {
  renderPrimitiveConstraints,
  typeExpression,
} from './validations/render-primitives.js';
import { renderStringConstraints } from './validations/render-strings.js';
import {
  renderAllOf,
  renderUnionConstraint,
} from './validations/render-unions.js';
import type { ChildFunctions } from './validations/types.js';
import { indent } from './validations/render-utils.js';

class MakerRenderer {
  #counter = 0;
  #functions: string[] = [];
  #nodeNames = new WeakMap<NormalizedSchema, string>();
  #nodeSignatures = new Map<string, string>();
  #referencedSchemas = new Set<string>();
  #schemaNames: Set<string>;

  constructor(model: OpenApiModel) {
    this.#schemaNames = new Set(model.schemas.map(({ name }) => name));
  }

  render(
    name: string,
    schema: NormalizedSchema,
    runtimeImport: string
  ): string {
    const rootValidator = this.#emitNode(schema);
    const makerImports = [...this.#referencedSchemas]
      .sort()
      .map((reference) => `import { make${reference} } from './${reference}';`)
      .join('\n');

    return `/**
 * Generated by openapi-contract-kit.
 * Do not edit directly.
 */

import type { Result, ValidationIssue, ValidationPath } from ${JSON.stringify(runtimeImport)};
import type { ${name} } from '../quickpay-api';
${makerImports}${makerImports.length > 0 ? '\n' : ''}

${this.#functions.join('\n\n')}

function validate${name}(
  value: unknown,
  path: ValidationPath,
  errors: ValidationIssue[]
): value is ${name} {
  return ${rootValidator}(value, path, errors);
}

export function make${name}(input: unknown): Result<${name}> {
  const errors: ValidationIssue[] = [];

  if (!validate${name}(input, [], errors)) {
    return { ok: false, errors };
  }

  return { ok: true, value: input };
}
`;
  }

  #emitNode(schema: NormalizedSchema): string {
    const existing = this.#nodeNames.get(schema);
    if (existing !== undefined) {
      return existing;
    }
    const signature = JSON.stringify(schema, (key, value: unknown) =>
      key === 'location' ? undefined : value
    );
    const matchingNode = this.#nodeSignatures.get(signature);
    if (matchingNode !== undefined) {
      this.#nodeNames.set(schema, matchingNode);
      return matchingNode;
    }

    const functionName = `validateNode${this.#counter}`;
    this.#counter += 1;
    this.#nodeNames.set(schema, functionName);
    this.#nodeSignatures.set(signature, functionName);

    const childFunctions = this.#createChildFunctions(schema);
    const body = this.#renderNodeBody(schema, childFunctions);
    this.#functions.push(
      `function ${functionName}(\n  value: unknown,\n  path: ValidationPath,\n  errors: ValidationIssue[]\n): boolean {\n${indent(body).join('\n')}\n}`
    );
    return functionName;
  }

  #createChildFunctions(schema: NormalizedSchema): ChildFunctions {
    if (schema.booleanSchema !== null) {
      return {
        additionalProperties: null,
        allOf: [],
        anyOf: [],
        items: null,
        oneOf: [],
        properties: [],
        reference: null,
      };
    }

    return {
      additionalProperties:
        typeof schema.additionalProperties === 'boolean'
          ? null
          : this.#emitNode(schema.additionalProperties),
      allOf: schema.allOf.map((child) => this.#emitNode(child)),
      anyOf: schema.anyOf.map((child) => this.#emitNode(child)),
      items: schema.items === null ? null : this.#emitNode(schema.items),
      oneOf: schema.oneOf.map((child) => this.#emitNode(child)),
      properties: schema.properties.map((property) => ({
        ...property,
        functionName: this.#emitNode(property.schema),
      })),
      reference:
        schema.reference === null
          ? null
          : this.#registerReference(schema.reference),
    };
  }

  #registerReference(reference: string): string {
    if (!this.#schemaNames.has(reference)) {
      throw new Error(`Unknown schema model reference "${reference}"`);
    }
    this.#referencedSchemas.add(reference);
    return reference;
  }

  #renderNodeBody(
    schema: NormalizedSchema,
    children: ChildFunctions
  ): string[] {
    const lines = ['const errorCount = errors.length;'];

    if (schema.booleanSchema !== null) {
      if (schema.booleanSchema) {
        lines.push('return true;');
      } else {
        lines.push(
          `errors.push({ path, keyword: 'falseSchema', message: 'Value is not allowed' });`,
          'return false;'
        );
      }
      return lines;
    }

    if (children.reference !== null) {
      lines.push(
        `const referenceResult = make${children.reference}(value);`,
        `if (!referenceResult.ok) {`,
        ...indent([
          `for (const issue of referenceResult.errors) {`,
          ...indent([
            `errors.push({ ...issue, path: [...path, ...issue.path] });`,
          ]),
          `}`,
        ]),
        `}`
      );
    }

    if (schema.types !== null) {
      const expected = schema.types
        .map((type) => typeExpression(type))
        .join(' || ');
      lines.push(
        `if (!(${expected})) {`,
        ...indent([
          `errors.push({ path, keyword: 'type', message: ${JSON.stringify(
            `Expected ${schema.types.join(' or ')}`
          )} });`,
          'return false;',
        ]),
        '}'
      );
    }

    renderPrimitiveConstraints(lines, schema.constValue, schema.enumValues);
    renderAllOf(lines, children.allOf);
    renderUnionConstraint(lines, 'anyOf', children.anyOf, false);
    renderUnionConstraint(lines, 'oneOf', children.oneOf, true);
    renderStringConstraints(lines, schema);
    renderNumberConstraints(lines, schema);
    renderArrayConstraints(lines, children.items);
    renderObjectConstraints(lines, schema, children);

    lines.push('return errors.length === errorCount;');
    return lines;
  }
}

export function emitSchemaMakers(
  model: OpenApiModel,
  config: GeneratorConfig
): Map<string, string> {
  const files = new Map<string, string>();

  for (const { name, schema } of model.schemas) {
    const renderer = new MakerRenderer(model);
    files.set(
      `schemas/${name}.ts`,
      renderer.render(name, schema, config.runtimeImport)
    );
  }

  return files;
}
