function renderLiteral(value) {
  return JSON.stringify(value);
}

function parenthesise(type) {
  return type.includes(' | ') || type.includes(' & ') ? `(${type})` : type;
}

function renderObjectType(schema) {
  if (schema.properties.length === 0) {
    if (
      schema.additionalProperties !== true &&
      schema.additionalProperties !== false
    ) {
      return `Record<string, ${renderSchemaType(schema.additionalProperties)}>`;
    }
    return 'Record<string, unknown>';
  }

  const properties = schema.properties.map((property) => {
    const optional = property.required ? '' : '?';
    return `  ${JSON.stringify(property.name)}${optional}: ${renderSchemaType(property.schema)};`;
  });
  return `{\n${properties.join('\n')}\n}`;
}

function renderBasicType(type, schema) {
  switch (type) {
    case 'array': {
      const itemType =
        schema.items === null ? 'unknown' : renderSchemaType(schema.items);
      return `Array<${itemType}>`;
    }
    case 'boolean':
      return 'boolean';
    case 'integer':
    case 'number':
      return 'number';
    case 'null':
      return 'null';
    case 'object':
      return renderObjectType(schema);
    case 'string':
      return 'string';
    default:
      throw new Error(`Unsupported normalised schema type "${type}"`);
  }
}

export function renderSchemaType(schema) {
  if (schema.booleanSchema === false) {
    return 'never';
  }
  if (schema.booleanSchema === true) {
    return 'unknown';
  }

  const intersections = [];

  if (schema.reference !== null) {
    intersections.push(schema.reference);
  }
  if (schema.constValue !== undefined) {
    intersections.push(renderLiteral(schema.constValue));
  } else if (schema.enumValues !== null) {
    intersections.push(schema.enumValues.map(renderLiteral).join(' | '));
  } else if (schema.types !== null) {
    intersections.push(
      schema.types.map((type) => renderBasicType(type, schema)).join(' | ')
    );
  }

  for (const child of schema.allOf) {
    intersections.push(renderSchemaType(child));
  }
  if (schema.oneOf.length > 0) {
    intersections.push(schema.oneOf.map(renderSchemaType).join(' | '));
  }
  if (schema.anyOf.length > 0) {
    intersections.push(schema.anyOf.map(renderSchemaType).join(' | '));
  }

  const meaningful = intersections.filter((type) => type !== 'unknown');
  if (meaningful.length === 0) {
    return 'unknown';
  }

  return meaningful.map(parenthesise).join(' & ');
}

export function emitRootTypes(model) {
  const declarations = model.schemas.flatMap(({ name, schema }) => [
    `export type ${name} = ${renderSchemaType(schema)};`,
    `export type ShapeOf${name} = ${name};`,
  ]);

  return `/**
 * Generated by openapi-contract-kit.
 * Do not edit directly.
 */

${declarations.join('\n\n')}
`;
}
