import type {
  GeneratorConfig,
  NormalizedSchema,
  OpenApiModel,
} from './types.js';
import { renderArrayConstraints } from './validations/render-arrays.js';
import { renderNumberConstraints } from './validations/render-numbers.js';
import { renderObjectConstraints } from './validations/render-objects.js';
import {
  renderPrimitiveConstraints,
  typeExpression,
} from './validations/render-primitives.js';
import { renderStringConstraints } from './validations/render-strings.js';
import {
  renderAllOf,
  renderUnionConstraint,
} from './validations/render-unions.js';
import type { ChildFunctions } from './validations/types.js';
import { indent } from './validations/render-utils.js';

class ValidatorRenderer {
  #counter = 0;
  #functions: string[] = [];
  #nodeNames = new WeakMap<NormalizedSchema, string>();
  #nodeSignatures = new Map<string, string>();
  #schemaNames: Set<string>;

  constructor(model: OpenApiModel) {
    this.#schemaNames = new Set(model.schemas.map(({ name }) => name));
  }

  render(model: OpenApiModel, config: GeneratorConfig): string {
    const typeNames = model.schemas.map(({ name }) => name).join(', ');
    const roots = model.schemas.map(({ name, schema }) => ({
      name,
      validator: this.#emitNode(schema),
    }));
    const namedValidators = roots.map(
      ({ name, validator }) => `export function validate${name}(
        value: unknown,
        path: ValidationPath,
        errors: ValidationIssue[]
      ): value is ${name} {
        return ${validator}(value, path, errors);
      }`
    );

    return `/**
      * Generated by openapi-contract-kit.
      * Do not edit directly.
      */

      import type { ValidationIssue, ValidationPath } from ${JSON.stringify(config.runtimeImport)};
      import type { ${typeNames} } from '../${config.typesFile.slice(0, -3)}';

      ${[...this.#functions, ...namedValidators].join('\n\n')}
      `;
  }

  #emitNode(schema: NormalizedSchema): string {
    const existing = this.#nodeNames.get(schema);
    if (existing !== undefined) return existing;

    const signature = JSON.stringify(schema, (key, value: unknown) =>
      key === 'location' ? undefined : value
    );
    const matchingNode = this.#nodeSignatures.get(signature);
    if (matchingNode !== undefined) {
      this.#nodeNames.set(schema, matchingNode);
      return matchingNode;
    }

    const functionName = `validateNode${this.#counter}`;
    this.#counter += 1;
    this.#nodeNames.set(schema, functionName);
    this.#nodeSignatures.set(signature, functionName);

    const childFunctions = this.#createChildFunctions(schema);
    const body = this.#renderNodeBody(schema, childFunctions);
    this.#functions.push(
      `function ${functionName}(\n  value: unknown,\n  path: ValidationPath,\n  errors: ValidationIssue[]\n): boolean {\n${indent(body).join('\n')}\n}`
    );
    return functionName;
  }

  #createChildFunctions(schema: NormalizedSchema): ChildFunctions {
    if (schema.booleanSchema !== null) {
      return {
        additionalProperties: null,
        allOf: [],
        anyOf: [],
        items: null,
        oneOf: [],
        properties: [],
        reference: null,
      };
    }

    return {
      additionalProperties:
        typeof schema.additionalProperties === 'boolean'
          ? null
          : this.#emitNode(schema.additionalProperties),
      allOf: schema.allOf.map((child) => this.#emitNode(child)),
      anyOf: schema.anyOf.map((child) => this.#emitNode(child)),
      items: schema.items === null ? null : this.#emitNode(schema.items),
      oneOf: schema.oneOf.map((child) => this.#emitNode(child)),
      properties: schema.properties.map((property) => ({
        ...property,
        functionName: this.#emitNode(property.schema),
      })),
      reference:
        schema.reference === null
          ? null
          : this.#registerReference(schema.reference),
    };
  }

  #registerReference(reference: string): string {
    if (!this.#schemaNames.has(reference)) {
      throw new Error(`Unknown schema model reference "${reference}"`);
    }
    return reference;
  }

  #renderNodeBody(
    schema: NormalizedSchema,
    children: ChildFunctions
  ): string[] {
    const lines = ['const errorCount = errors.length;'];

    if (schema.booleanSchema !== null) {
      if (schema.booleanSchema) {
        lines.push('return true;');
      } else {
        lines.push(
          `errors.push({ path, keyword: 'falseSchema', message: 'Value is not allowed' });`,
          'return false;'
        );
      }
      return lines;
    }

    if (children.reference !== null) {
      lines.push(`validate${children.reference}(value, path, errors);`);
    }

    if (schema.types !== null) {
      const expected = schema.types
        .map((type) => typeExpression(type))
        .join(' || ');
      lines.push(
        `if (!(${expected})) {`,
        ...indent([
          `errors.push({ path, keyword: 'type', message: ${JSON.stringify(
            `Expected ${schema.types.join(' or ')}`
          )} });`,
          'return false;',
        ]),
        '}'
      );
    }

    renderPrimitiveConstraints(lines, schema.constValue, schema.enumValues);
    renderAllOf(lines, children.allOf);
    renderUnionConstraint(lines, 'anyOf', children.anyOf, false);
    renderUnionConstraint(lines, 'oneOf', children.oneOf, true);
    renderStringConstraints(lines, schema);
    renderNumberConstraints(lines, schema);
    renderArrayConstraints(lines, children.items);
    renderObjectConstraints(lines, schema, children);

    lines.push('return errors.length === errorCount;');
    return lines;
  }
}

function renderMaker(
  name: string,
  runtimeImport: string,
  typesFile: string
): string {
  return `/**
 * Generated by openapi-contract-kit.
 * Do not edit directly.
 */

import type { Result, ValidationIssue } from ${JSON.stringify(runtimeImport)};
import type { ShapeOf${name} } from '../${typesFile.slice(0, -3)}';
import { validate${name} } from './validators';

export function make${name}(input: unknown): Result<ShapeOf${name}> {
  const errors: ValidationIssue[] = [];

  if (!validate${name}(input, [], errors)) {
    return { ok: false, errors };
  }

  return { ok: true, value: input };
}
`;
}

export function emitSchemaMakers(
  model: OpenApiModel,
  config: GeneratorConfig
): Map<string, string> {
  const files = new Map<string, string>();
  const renderer = new ValidatorRenderer(model);

  files.set('schemas/validators.ts', renderer.render(model, config));
  for (const { name } of model.schemas) {
    files.set(
      `schemas/${name}.ts`,
      renderMaker(name, config.runtimeImport, config.typesFile)
    );
  }

  return files;
}
