import type {
  GeneratorConfig,
  OpenApiModel,
  ResponseModel,
} from './types.js';

function renderResponseType(responses: readonly ResponseModel[]): string {
  if (responses.length === 0) {
    return 'never';
  }

  return responses
    .map(({ schemaName, status }) => {
      const bodyType = schemaName ?? 'null';
      return `{ readonly status: ${status}; readonly body: ${bodyType} }`;
    })
    .join(' | ');
}

function renderStatusCases(responses: readonly ResponseModel[]): string {
  const lines: string[] = [];

  for (const response of responses) {
    lines.push(`    case ${response.status}: {`);
    if (response.schemaName === null) {
      lines.push(
        `      if (parts.body !== null) {`,
        `        return failure(['body'], 'nullBody', 'Expected a null response body');`,
        `      }`,
        `      return { ok: true, value: { status: ${response.status}, body: null } };`
      );
    } else {
      lines.push(
        `      const result = make${response.schemaName}(parts.body);`,
        `      if (!result.ok) {`,
        `        return result;`,
        `      }`,
        `      return { ok: true, value: { status: ${response.status}, body: result.value } };`
      );
    }
    lines.push('    }');
  }

  lines.push(
    `    default:`,
    `      return failure(['status'], 'status', 'Undocumented response status');`
  );
  return lines.join('\n');
}

function emitEndpoint(
  operation: OpenApiModel['operations'][number],
  config: GeneratorConfig
): string {
  const successResponses = operation.responses.filter(
    (response) => response.isSuccess
  );
  const errorResponses = operation.responses.filter(
    (response) => !response.isSuccess
  );
  const schemaNames = new Set<string>();

  if (operation.request.schemaName !== null) {
    schemaNames.add(operation.request.schemaName);
  }
  for (const response of operation.responses) {
    if (response.schemaName !== null) {
      schemaNames.add(response.schemaName);
    }
  }

  const sortedSchemaNames = [...schemaNames].sort();
  const typeImport =
    sortedSchemaNames.length === 0
      ? ''
      : `import type { ${sortedSchemaNames.join(', ')} } from '../quickpay-api';\n`;
  const makerImports = sortedSchemaNames
    .map((name) => `import { make${name} } from '../schemas/${name}';`)
    .join('\n');
  const requestType = operation.request.schemaName ?? 'null';
  const requestMaker =
    operation.request.schemaName === null
      ? `export function makeRequest(input: unknown): Result<null> {
  if (input !== null) {
    return failure([], 'nullBody', 'Expected null');
  }

  return { ok: true, value: null };
}`
      : `export const makeRequest = make${operation.request.schemaName};`;

  return `/**
 * Generated by openapi-contract-kit.
 * Do not edit directly.
 */

import type { Result, ValidationPath } from ${JSON.stringify(config.runtimeImport)};
${typeImport}${makerImports}${makerImports.length > 0 ? '\n' : ''}
export const URL = ${JSON.stringify(operation.path)};
export const METHOD = ${JSON.stringify(operation.method)};
export const OPERATION_ID = ${JSON.stringify(operation.operationId)};

export type ShapeOfRequest = ${requestType};
export type ShapeOfSuccessResponse = ${renderResponseType(successResponses)};
export type ShapeOfErrorResponse = ${renderResponseType(errorResponses)};
export type ShapeOfResponse = ShapeOfSuccessResponse | ShapeOfErrorResponse;

type ResponseParts = {
  readonly status: number;
  readonly body: unknown;
};

function failure<T>(
  path: ValidationPath,
  keyword: string,
  message: string
): Result<T> {
  return { ok: false, errors: [{ path, keyword, message }] };
}

function readResponse(input: unknown): ResponseParts | null {
  if (typeof input !== 'object' || input === null || Array.isArray(input)) {
    return null;
  }
  if (
    !Object.prototype.hasOwnProperty.call(input, 'status') ||
    !Object.prototype.hasOwnProperty.call(input, 'body')
  ) {
    return null;
  }

  const status = Reflect.get(input, 'status');
  if (typeof status !== 'number' || !Number.isInteger(status)) {
    return null;
  }

  return { status, body: Reflect.get(input, 'body') };
}

${requestMaker}

function makeSuccessResponseResult(input: unknown): Result<ShapeOfSuccessResponse> {
  const parts = readResponse(input);
  if (parts === null) {
    return failure([], 'response', 'Expected { status, body }');
  }

  switch (parts.status) {
${renderStatusCases(successResponses)}
  }
}

function makeErrorResponseResult(input: unknown): Result<ShapeOfErrorResponse> {
  const parts = readResponse(input);
  if (parts === null) {
    return failure([], 'response', 'Expected { status, body }');
  }

  switch (parts.status) {
${renderStatusCases(errorResponses)}
  }
}

function makeAnyResponse(input: unknown): Result<ShapeOfResponse> {
  const parts = readResponse(input);
  if (parts === null) {
    return failure([], 'response', 'Expected { status, body }');
  }

  return parts.status >= 200 && parts.status <= 299
    ? makeSuccessResponseResult(input)
    : makeErrorResponseResult(input);
}

export const makeResponse = Object.assign(makeAnyResponse, {
  success: makeSuccessResponseResult,
  error: makeErrorResponseResult,
});
`;
}

export function emitEndpointModules(
  model: OpenApiModel,
  config: GeneratorConfig
): Map<string, string> {
  return new Map(
    model.operations.map((operation) => [
      `endpoints/${operation.name}.ts`,
      emitEndpoint(operation, config),
    ])
  );
}
