import type {
  NormalizedSchema,
  OpenApiModel,
  SchemaType,
  StandardSchema,
} from './types.js';

function renderLiteral(value: boolean | null | number | string): string {
  return JSON.stringify(value);
}

function parenthesise(type: string): string {
  return type.includes(' | ') || type.includes(' & ') ? `(${type})` : type;
}

function renderObjectType(schema: StandardSchema): string {
  if (schema.properties.length === 0) {
    if (typeof schema.additionalProperties !== 'boolean') {
      return `Record<string, ${renderSchemaType(schema.additionalProperties)}>`;
    }
    return 'Record<string, unknown>';
  }

  const properties = schema.properties.map((property) => {
    const optional = property.required ? '' : '?';
    return `  ${JSON.stringify(property.name)}${optional}: ${renderSchemaType(property.schema)};`;
  });
  return `{\n${properties.join('\n')}\n}`;
}

function renderBasicType(type: SchemaType, schema: StandardSchema): string {
  switch (type) {
    case 'array': {
      const itemType =
        schema.items === null ? 'unknown' : renderSchemaType(schema.items);
      return `Array<${itemType}>`;
    }
    case 'boolean':
      return 'boolean';
    case 'integer':
    case 'number':
      return 'number';
    case 'null':
      return 'null';
    case 'object':
      return renderObjectType(schema);
    case 'string':
      return 'string';
    default: {
      const exhaustive: never = type;
      throw new Error(`Unsupported normalised schema type "${exhaustive}"`);
    }
  }
}

export function renderSchemaType(schema: NormalizedSchema): string {
  if (schema.booleanSchema !== null) {
    return schema.booleanSchema ? 'unknown' : 'never';
  }

  const intersections: string[] = [];

  if (schema.reference !== null) {
    intersections.push(schema.reference);
  }
  if (schema.constValue !== undefined) {
    intersections.push(renderLiteral(schema.constValue));
  } else if (schema.enumValues !== null) {
    intersections.push(schema.enumValues.map(renderLiteral).join(' | '));
  } else if (schema.types !== null) {
    intersections.push(
      schema.types.map((type) => renderBasicType(type, schema)).join(' | ')
    );
  }

  for (const child of schema.allOf) {
    intersections.push(renderSchemaType(child));
  }
  if (schema.oneOf.length > 0) {
    intersections.push(schema.oneOf.map(renderSchemaType).join(' | '));
  }
  if (schema.anyOf.length > 0) {
    intersections.push(schema.anyOf.map(renderSchemaType).join(' | '));
  }

  const meaningful = intersections.filter((type) => type !== 'unknown');
  if (meaningful.length === 0) {
    return 'unknown';
  }

  return meaningful.map(parenthesise).join(' & ');
}

export function emitRootTypes(model: OpenApiModel): string {
  const declarations = model.schemas.flatMap(({ name, schema }) => [
    `export type ${name} = ${renderSchemaType(schema)};`,
    `export type ShapeOf${name} = ${name};`,
  ]);
  const operationDeclarations = model.operations.flatMap((operation) => {
    const requestType = operation.request.schemaName ?? 'null';
    const responseTypes = [
      ...new Set(
        operation.responses.map(({ schemaName }) => schemaName ?? 'null')
      ),
    ].join(' | ');
    const statuses = operation.responses
      .map(({ status }) => status)
      .join(' | ');
    return [
      `export type ${operation.name}Request = ${requestType};`,
      `export type ShapeOf${operation.name}Request = ${operation.name}Request;`,
      `export type ${operation.name}Response = ${responseTypes};`,
      `export type ShapeOf${operation.name}Response = ${operation.name}Response;`,
      `export type ShapeOf${operation.name}ResponseStatus = ${statuses};`,
      `export declare namespace ShapeOf${operation.name} {\n  export type Request = ShapeOf${operation.name}Request;\n  export type Response = ShapeOf${operation.name}Response;\n  export type ResponseStatus = ShapeOf${operation.name}ResponseStatus;\n}`,
    ];
  });

  return `/**
 * Generated by openapi-contract-kit.
 * Do not edit directly.
 */

${[...declarations, ...operationDeclarations].join('\n\n')}
`;
}
